
const nameBoxAlpha = 0.8;
const effectHeaderAlpha = 0.9;
export const attrColors = {
    w: { base: "white", fa: "w-fa", nameBoxColor: `rgba(242, 216, 97, ${nameBoxAlpha})`, effectHeaderColor: `rgba(242, 216, 97, ${effectHeaderAlpha})` },
    r: { base: "red", fa: "r-fa", nameBoxColor: `rgba(255, 94, 94, ${nameBoxAlpha})`, effectHeaderColor: `rgba(255, 94, 94, ${effectHeaderAlpha})` },
    u: { base: "blue", fa: "u-fa", nameBoxColor: `rgba(106, 198, 218, ${nameBoxAlpha})`, effectHeaderColor: `rgba(106, 198, 218, ${effectHeaderAlpha})` },
    g: { base: "green", fa: "g-fa", nameBoxColor: `rgba(107, 177, 76, ${nameBoxAlpha})`, effectHeaderColor: `rgba(107, 177, 76, ${effectHeaderAlpha})` },
    b: { base: "black", fa: "b-fa", nameBoxColor: `rgba(133, 93, 145, ${nameBoxAlpha})`, effectHeaderColor: `rgba(133, 93, 145, ${effectHeaderAlpha})` },
    v: { base: "void", fa: "v-fa", nameBoxColor: `rgba(143, 143, 143, ${nameBoxAlpha})`, effectHeaderColor: `rgba(143, 143, 143, ${effectHeaderAlpha})` },
};

export const attrCoords = [
    { x: 102.5, y: 67 },
    { x: 64, y: 98.5 },
    { x: 143.5, y: 100 },
    { x: 78.5, y: 140.5 },
    { x: 126.5, y: 142 },
    { x: 117, y: 124.5 }, // void cost
];

export const imgFiles = {
    "0": ["0.png", "0-fa.png"],
    "1": ["1.png", "1-fa.png"],
    "2": ["2.png", "2-fa.png"],
    "3": ["3.png", "3-fa.png"],
    "4": ["4.png", "4-fa.png"],
    "5": ["5.png", "5-fa.png"],
    "6": ["6.png", "6-fa.png"],
    "7": ["7.png", "7-fa.png"],
    "8": ["8.png", "8-fa.png"],
    "9": ["9.png", "9-fa.png"],
    "activate": ["lapis-activate.png", "lapis-activate-fa.png"],
    "arrow": ["arrow.png", "arrow-fa.png"],
    "ascend": ["lapis-ascend.png", "lapis-ascend.png"], // no fa
    "awakening": ["lapis-awakening.png", "lapis-awakening-fa.png"],
    "b": ["black.png", "black-fa.png"],
    "bane": ["valhalla-bane.png", "valhalla-bane-fa.png"],
    "barrier": ["lapis-barrier.png", "lapis-barrier-fa.png"],
    "bestow": ["lapis-bestow.png", "lapis-bestow-fa.png"],
    "bloodlust": ["lapis-bloodlust.png", "lapis-bloodlust-fa.png"],
    "brown": ["brown.png", "brown-fa.png"],
    "calmness": ["lapis-calmness.png", "lapis-calmness-fa.png"],
    "colorless": ["colorless.png", "colorless-fa.png"],
    "continuous": ["lapis-continuous.png", "lapis-continuous-fa.png"],
    "crest": ["reiya-crest.png", "reiya-crest-fa.png"],
    "dive": ["lapis-dive.png", "lapis-dive-fa.png"],
    "divinity": ["valhalla-divinity.png", "valhalla-divinity-fa.png"],
    "dragonemblem": ["valhalla-dragonemblem.png", "valhalla-dragonemblem-fa.png"],
    "drain": ["reiya-drain.png", "reiya-drain-fa.png"],
    "energize": ["lapis-energize.png", "lapis-energize-fa.png"],
    "enter": ["lapis-enter.png", "lapis-enter-fa.png"],
    "error": ["error.png", "error-fa.png"],
    "eternal": ["valhalla-eternal.png", "valhalla-eternal-fa.png"],
    "evolution": ["lapis-evolution.png", "lapis-evolution-fa.png"],
    "explode": ["lapis-explode.png", "lapis-explode-fa.png"],
    "exploration": ["saga-exploration.png", "saga-exploration-fa.png"],
    "faith": ["valhalla-faith.png", "valhalla-faith-fa.png"],
    "firststrike": ["lapis-firststrike.png", "lapis-firststrike-fa.png"],
    "flying": ["lapis-flying.png", "lapis-flying-fa.png"],
    "force": ["lapis-force.png", "lapis-force-fa.png"],
    "g": ["green.png", "green-fa.png"],
    "gem": ["gem.png", "gem-fa.png"],
    "grimoire": ["reiya-grimoire.png", "reiya-grimoire-fa.png"],
    "guidance": ["saga-guidance.png", "saga-guidance-fa.png"],
    "imperishable": ["lapis-imperishable.png", "lapis-imperishable-fa.png"],
    "incarnation": ["lapis-incarnation.png", "lapis-incarnation-fa.png"],
    "inheritance": ["lapis-inheritance.png", "lapis-inheritance-fa.png"],
    "jactivate": ["lapis-jactivate.png", "lapis-jactivate-fa.png"],
    "judgment": ["lapis-judgment.png", "lapis-judgment-fa.png"],
    "legend": ["reiya-legend.png", "reiya-legend-fa.png"],
    "lifeburst": ["lifeburst.png", "lifeburst.png"], // no fa
    "limit": ["lapis-limit.png", "lapis-limit-fa.png"],
    "limitbreak": ["lapis-limitbreak.png", "lapis-limitbreak-fa.png"],
    "mana": ["lapis-mana.png", "lapis-mana-fa.png"],
    "mobilize": ["reiya-mobilize.png", "reiya-mobilize-fa.png"],
    "m": ["moon.png", "moon-fa.png"],
    "mythic": ["alice-mythic.png", "alice-mythic-fa.png"],
    "null": ["reiya-null.png", "reiya-null-fa.png"],
    "origin-break": ["origin-break.png", "origin-break-fa.png"],
    "passion": ["lapis-passion.png", "lapis-passion-fa.png"],
    "pierce": ["lapis-pierce.png", "lapis-pierce-fa.png"],
    "precision": ["lapis-precision.png", "lapis-precision-fa.png"],
    "quickcast": ["lapis-quickcast.png", "lapis-quickcast-fa.png"],
    "r": ["red.png", "red-fa.png"],
    "remnant": ["lapis-remnant.png", "lapis-remnant-fa.png"],
    "resonance": ["lapis-resonance.png", "lapis-resonance-fa.png"],
    "rest": ["rest.png", "rest-fa.png"],
    "revenge": ["saga-revenge.png", "saga-revenge-fa.png"],
    "rune": ["valhalla-rune.png", "valhalla-rune-fa.png"],
    "seal": ["lapis-seal.png", "lapis-seal-fa.png"],
    "shift": ["lapis-shift.png", "lapis-shift-fa.png"],
    "stealth": ["lapis-stealth.png", "lapis-stealth-fa.png"],
    "stranger": ["alice-stranger.png", "alice-stranger-fa.png"],
    "swiftness": ["lapis-swiftness.png", "lapis-swiftness-fa.png"],
    "tag": ["saga-tag.png", "saga-tag-fa.png"],
    "targetattack": ["lapis-targetattack.png", "lapis-targetattack-fa.png"],
    "t": ["time.png", "time-fa.png"],
    "torrent": ["lapis-torrent.png", "lapis-torrent-fa.png"],
    "trigger": ["lapis-trigger.png", "lapis-trigger-fa.png"],
    "u": ["blue.png", "blue-fa.png"],
    "vermilion": ["valhalla-vermilion.png", "valhalla-vermilion-fa.png"],
    "v": ["void.png", "void-fa.png"],
    "w": ["white.png", "white-fa.png"],
    "willofdespair": ["lapis-willofdespair.png", "lapis-willofdespair-fa.png"],
    "willofhope": ["lapis-willofhope.png", "lapis-willofhope-fa.png"],
    "x": ["x.png", "x-fa.png"],
}
